<?php

return [
    'houses' => [
        [
            'title' => 'La Casa di Luce',
            'address' => 'Via del Mare, 00126 Roma',
            'latitude' => '41.79246',
            'longitude' => '12.38622',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 100,
            'description' => 'Un\' accogliente dimora con ampie finestre che permettono alla luce naturale di riempire gli spazi, offrendo un ambiente luminoso e rilassante.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Vista Mare Sereno',
            'address' => 'Piazza del Popolo, 00187 Roma',
            'latitude' => '41.91048',
            'longitude' => '12.47623',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Una casa affacciata sul mare con una vista mozzafiato che offre una quiete e serenità uniche, ideale per godersi tramonti indimenticabili.',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Rifugio Montano',
            'address' => 'Via Napoleone, 20121 Milano',
            'latitude' => '45.46818',
            'longitude' => '9.19532',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Un accogliente rifugio situato tra le montagne, perfetto per gli amanti della natura e delle escursioni',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Dolce Tranquillità',
            'address' => 'Via Stazione, 32043 Cortina d\'Ampezzo',
            'latitude' => '46.53914',
            'longitude' => '12.13643',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 150,
            'description' => 'Una casa che promette una pausa rilassante dalla frenesia quotidiana, offrendo un ambiente tranquillo e sereno',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Casa Soleggiata',
            'address' => 'Via Monte Napoleone, 20121 Milano',
            'latitude' => '45.46818',
            'longitude' => '9.19532',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Una residenza accogliente e luminosa, baciata dal sole tutto il giorno, perfetta per godersi la calda atmosfera diurna',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Paradiso Sospeso',
            'address' => 'Via Faloria, 32043 Cortina d\'Ampezzo',
            'latitude' => '46.53269',
            'longitude' => '12.14363',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 150,
            'description' => 'Una casa incantevole, apparentemente sospesa nel tempo e nello spazio, ideale per una fuga romantica',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Angolo di Pace',
            'address' => 'Piazza Navona, 00186 Roma',
            'latitude' => '41.89913',
            'longitude' => '12.4732',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 80,
            'description' => 'Un luogo dove ritrovare l\'armonia interiore e godersi un ambiente calmo e pacifico, lontano dal caos della vita quotidiana',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Rifugio delle Colline',
            'address' => 'Via del Castello, 53037 San Gimignano SI, Italia',
            'latitude' => '43.46754',
            'longitude' => '11.04466',
            'beds' => 10,
            'rooms' => 5,
            'bathrooms' => 5,
            'sq_meters' => 400,
            'description' => 'Una dimora affascinante immersa nelle colline, offrendo un rifugio ideale per rigenerarsi e godere della natura circostante',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Nido Accogliente',
            'address' => 'Campo San Polo, 30125 Venezia, Italia',
            'latitude' => '45.43735',
            'longitude' => '12.3296',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 80,
            'description' => 'Una casa intima e accogliente, perfetta per una fuga romantica o un soggiorno tranquillo e confortevole',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Cielo Blu Residenza',
            'address' => 'Via San Giovanni, 50028 Tavarnelle Val di Pesa FI, Italia',
            'latitude' => '43.56389',
            'longitude' => '11.17425',
            'beds' => 8,
            'rooms' => 4,
            'sq_meters' => 200,
            'bathrooms' => 4,
            'description' => 'Una residenza che offre un\'esperienza unica sotto un cielo sempre blu, ideale per un soggiorno di relax e serenità',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Vento Marinaio',
            'address' => 'Via Mazzini, 19018 Vernazza SP, Italia',
            'latitude' => '44.13448',
            'longitude' => '9.68334',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Una residenza caratterizzata da una brezza marina rinfrescante e un\'atmosfera che richiama il mare, perfetta per chi ama il contatto con l\'oceano',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Cottage Incantato',
            'address' => 'Via Del Porto, 06069 Tuoro sul Trasimeno PG, Italia',
            'latitude' => '43.20603',
            'longitude' => '12.07734',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 3,
            'sq_meters' => 150,
            'description' => 'Un\'affascinante dimora dal fascino fiabesco, immersa in un giardino incantato, perfetta per vivere una favola moderna',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casale Fiorito',
            'address' => 'Piazza della Signoria, 50122 Firenze FI, Italia',
            'latitude' => '43.76954',
            'longitude' => '11.25598',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Un antico casale circondato da giardini fioriti e profumati, offrendo un\'oasi di tranquillità e bellezza',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Rifugio Selvaggio',
            'address' => 'Via Regina, 22010 Cernobio, Italia',
            'latitude' => '45.8523',
            'longitude' => '9.08894',
            'beds' => 8,
            'rooms' => 4,
            'bathrooms' => 3,
            'sq_meters' => 200,
            'description' => 'Una residenza avvolta dalla natura selvaggia e incontaminata, ideale per gli amanti dell\'avventura e della privacy',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Alba Magica',
            'address' => 'Corso Italia, 80067 Sorrento NA, Italia',
            'latitude' => '40.62676',
            'longitude' => '14.38085',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 100,
            'description' => 'Una casa dove ogni alba regala uno spettacolo mozzafiato, immergendo gli ospiti in una magia mattutina senza pari',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Oasi Verde',
            'address' => 'Via del Mandarino, 91010 San Vito Lo Capo TP, Italia',
            'latitude' => '38.13129',
            'longitude' => '12.73482',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Un\'incantevole oasi di verde e tranquillità, ideale per chi cerca una fuga dalla vita cittadina',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casa dei Sogni',
            'address' => 'Via dei Melograni, 50142 Firenze',
            'latitude' => '43.77741',
            'longitude' => '11.22011',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Una dimora che sembra uscita direttamente dai sogni, offrendo un ambiente confortevole e accogliente per creare ricordi indimenticabili',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Dimora Relax',
            'address' => 'Viale della Vittoria, 00122 Roma',
            'latitude' => '41.72929,',
            'longitude' => '12.28798',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 80,
            'description' => 'Una casa progettata per offrire il massimo relax, con spazi confortevoli e un\'atmosfera accogliente',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Mare e Monti Hideaway',
            'address' => 'Viale dei Pini, 50142 Firenze',
            'latitude' => '43.77924',
            'longitude' => '11.21495',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 90,
            'description' => 'Un rifugio nascosto tra il mare e le montagne, offrendo una varietà di esperienze naturali e paesaggi mozzafiato',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Palazzo della Quietudine',
            'address' => 'Viale Trento, 47921 Rimini',
            'latitude' => '44.06591',
            'longitude' => '12.5792',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 70,
            'description' => 'Una dimora maestosa che promette tranquillità assoluta e un\'esperienza di soggiorno regale',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Villa in campagna',
            'address' => 'Via delle Rose, 50025 Montespertoli',
            'latitude' => '43.69627,',
            'longitude' => '11.01391',
            'beds' => 10,
            'rooms' => 5,
            'bathrooms' => 4,
            'sq_meters' => 300,
            'description' => 'Splendida villa con piscina privata e vista sulla campagna toscana',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Monolocale nel centro storico',
            'address' => 'Via dei Benci, 50122 Firenze',
            'latitude' => '43.76767',
            'longitude' => '11.2594',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 30,
            'description' => 'Accogliente monolocale nel cuore del centro storico',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Villa degli Ulivi',
            'address' => 'Via degli Ulivi, 95123 Catania CT',
            'latitude' => '37.52557',
            'longitude' => '15.05628',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 100,
            'description' => 'Splendida villa immersa nel verde degli ulivi, con vista mozzafiato sul mare della Sicilia. Perfetta per una vacanza rilassante e lontana dal caos della città.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casa del Pescatore',
            'address' => 'Via del Mare, 97010 Modica RG',
            'latitude' => '36.7128',
            'longitude' => '14.77913',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Deliziosa casetta situata a pochi passi dal mare, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Appartamento Milano',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19226',
            'beds' => 4,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 80,
            'description' => 'Appartamento elegante in Piazza Duomo: Ampio appartamento con finiture di lusso, a pochi passi dalla Cattedrale di Milano.',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Suite degli ospiti',
            'address' => 'Via Giuseppe Mazzini, 20123 Milano MI',
            'latitude' => '45.46205',
            'longitude' => '9.18836',
            'beds' => 1,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Appartamento moderno vicino a Piazza Duomo: Appartamento di design con vista sulla Piazza Duomo, dotato di tutti i comfort.',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Appartamento luminoso',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19205',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 70,
            'description' => 'Appartamento accogliente in Piazza Duomo: Appartamento caldo e accogliente, arredato con gusto e posizionato in un palazzo storico.',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Appartamento',
            'address' => 'Via Larga, 12, 20122 Milano MI',
            'latitude' => '45.46185',
            'longitude' => '9.19234',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Monolocale accogliente a pochi passi da Piazza Duomo: Delizioso monolocale dallo stile contemporaneo, con vista sulla piazza più famosa di Milano.',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Stanza Privata',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19285',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Deliziosa casetta situata a pochi passi dal Duomo.',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Appartamento Duomo',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19625',
            'beds' => 7,
            'rooms' => 5,
            'bathrooms' => 3,
            'sq_meters' => 150,
            'description' => 'Attico di lusso in Piazza Duomo: Attico di design, con ampie vetrate panoramiche e una splendida terrazza privata con vista sulla Cattedrale di Milano.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Stanza in centro',
            'address' => 'Piazza del Liberty, 20121 Milano MI',
            'latitude' => '45.46532',
            'longitude' => '9.19421',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Monolocale accogliente: Delizioso monolocale dallo stile contemporaneo, con vista sulla piazza più famosa di Milano.',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Casa della musica',
            'address' => 'Piazza della Scala, 5, 20121 Milano MI',
            'latitude' => '45.46796',
            'longitude' => '9.18781',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Monolocale accogliente vicino al Teatrro alla Scala: Delizioso monolocale dallo stile contemporaneo, con vista sul teatro.',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento in centro',
            'address' => 'Via Guglielmo Marconi, Piazza Armando Diaz, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19225',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Loft esclusivo in Piazza Duomo: Luminoso loft di design con vista sulla Cattedrale di Milano, perfetto per chi cerca uno spazio unico e raffinato.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Appartamento vista Duomo',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.18825',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Loft esclusivo in Piazza Duomo: Luminoso loft di design con vista sulla Cattedrale di Milano',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Stanza singola',
            'address' => 'Via Cesare Cantù, 4, 20123 Milano MI',
            'latitude' => '45.46409',
            'longitude' => '9.18654',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Stanza a due passi dal centro di Milano',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casa City Life',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 90,
            'description' => 'Deliziosa casetta ideale per una famiglia in cerca di relax e tranquillità.',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento vista parco',
            'address' => 'Via Antonio Canova, 12, 20145 Milano MI',
            'latitude' => '45.47602',
            'longitude' => '9.16862',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Casa situata a pochi passi dal centro, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento vista City Life',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Delizioso appartamento situato a pochi passi dal centro di City Life, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Stanza singola City Life',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Deliziosa stanza a pochi passi dal centro di City Life, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto.',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento San Siro',
            'address' => 'Via Pasquale Stanislao Mancini, 5, 20148 Milano MI',
            'latitude' => '45.4781',
            'longitude' => '9.13745',
            'beds' => 5,
            'rooms' => 4,
            'bathrooms' => 4,
            'sq_meters' => 250,
            'description' => 'Delizioso appartamento situato a pochi passi dal centro di City Life, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Appartamento in centro',
            'address' => 'Via Guglielmo Marconi, Piazza Armando Diaz, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19225',
            'beds' => 4,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 80,
            'description' => 'Delizioso appartamento situato a pochi passi dal Duomo, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casa in City Life Milano',
            'address' => 'Via Alcuino, 20149 Milano MI',
            'latitude' => '45.4827',
            'longitude' => '9.15605',
            'beds' => 5,
            'rooms' => 3,
            'bathrooms' => 4,
            'sq_meters' => 250,
            'description' => 'Deliziosa casetta situata a pochi passi dalla City Life',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Residenze Libeskind',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47540',
            'longitude' => '9.15280',
            'beds' => 7,
            'rooms' => 6,
            'bathrooms' => 3,
            'sq_meters' => 250,
            'description' => 'Deliziosa casetta nel quartiere di Milano Libeskind',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Stanza in una Residenza Libeskind',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 1,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 30,
            'description' => 'Stanza confortevole in una delle meravigliose case Libeskind',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento del Pescatore',
            'address' => 'Fondamenta Fianco Ponte Lungo, 30133 Venezia VE',
            'latitude' => '45.426',
            'longitude' => '12.32897',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Appartamento accogliente sul canale della Giudecca',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'La Casa dei Canali',
            'address' => 'Fondamenta Fianco Ponte Lungo, 30133 Venezia VE',
            'latitude' => '45.426',
            'longitude' => '12.32897',
            'beds' => 5,
            'rooms' => 4,
            'bathrooms' => 3,
            'sq_meters' => 150,
            'description' => 'Casa sul canale dell\'isola Giudecca con vista su tutta Venezia',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'La Suite del Doge',
            'address' => 'Calle Città di Fano, 30133 Venezia VE',
            'latitude' => '45.4251',
            'longitude' => '12.33711',
            'beds' => 3,
            'rooms' => 1,
            'bathrooms' => 3,
            'sq_meters' => 150,
            'description' => 'Splendida Suite a Venezia, lusso e confort a non finire per passare un weekend di coppia romantico nelle città del Doge',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Stanza a Campo Santa Margherita',
            'address' => 'Sestiere Dorsoduro, 30123 Venezia VE',
            'latitude' => '45.4338',
            'longitude' => '12.32834',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Confrotevole stanza situata nel centro di Venezia, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto.',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Casa del Pescatore',
            'address' => 'Sestiere Dorsoduro, 30123 Venezia VE',
            'latitude' => '45.4338',
            'longitude' => '12.32436',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 80,
            'description' => 'Deliziosa casetta situata a pochi passi dal Grand Canal, ideale per una famiglia in visita a Venezia. Arredata con gusto e dotata di tutti i comfort.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casa del Pescatore',
            'address' => 'Fondamenta Zattere Al Ponte Lungo, 30123 Venezia VE',
            'latitude' => '45.43043',
            'longitude' => '12.32249',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 100,
            'description' => 'Appartamento sul Rio dei Carmini, vicino alla stazione San Basilio per spostarsi con il Traghetto.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casa nel cuore di Venezia',
            'address' => 'C. de Mezzo, 30125 Venezia VE',
            'latitude' => '45.43588',
            'longitude' => '12.33547',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 110,
            'description' => 'Casa accogliente nel cuore di Venezia. Situata a pochi passi dalla stazione per avere degli spostamenti comdi da e per la città.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Appartamento del Pescatore',
            'address' => 'Fondamenta Zattere Al Ponte Lungo, 30123 Venezia VE',
            'latitude' => '45.43053',
            'longitude' => '12.32249',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 90,
            'description' => 'Appartamento sul Rio dei Carmini, a pochi passi dalla zona Universitaria e vicino alla stazione San Basilio per spostarsi con il Traghetto.',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Stanza a Venezia',
            'address' => 'C. de le Altane, 30100 Venezia VE',
            'latitude' => '45.44377',
            'longitude' => '12.32241',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Stanza a venezia, semplice e accogliente per passare un ottima vacanza ',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento vista Piazza San Marco',
            'address' => 'S. Marco, 30124 Venezia VE',
            'latitude' => '45.4345',
            'longitude' => '12.33788',
            'beds' => 5,
            'rooms' => 4,
            'bathrooms' => 4,
            'sq_meters' => 150,
            'description' => 'Delizioso apartamento con vista San Marco, lusso e confort di ogni genere',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Villetta a Capri',
            'address' => 'Via Krupp, 80076 Capri NA',
            'latitude' => '40.5462',
            'longitude' => '14.23976',
            'beds' => 7,
            'rooms' => 5,
            'bathrooms' => 4,
            'sq_meters' => 290,
            'description' => 'Villetta a Capri con vista sui faraglioni .',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casa vista Capri',
            'address' => 'Via Krupp, 80076 Capri NA',
            'latitude' => '40.5422',
            'longitude' => '14.23978',
            'beds' => 5,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 150,
            'description' => 'Casa con vista mare, semplice e accogliente per passare un ottima vacanza in tranquillità.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Appartamento vista Mare',
            'address' => 'Via Crotta delle Felci, 80076 Capri NA',
            'latitude' => '40.54705',
            'longitude' => '14.23336',
            'beds' => 5,
            'rooms' => 4,
            'bathrooms' => 4,
            'sq_meters' => 150,
            'description' => 'Appartamento a pochi passi dalle famose spiagge di Capri con tutti i confort necesari.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Stanza a Capri',
            'address' => 'Via Crotta delle Felci, 80076 Capri NA',
            'latitude' => '40.54735',
            'longitude' => '14.23336',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 90,
            'description' => 'Stanza accogliente, arredamento moderno e vista mozzafiato.',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento vista Colosseo',
            'address' => 'Viale della Domus Aurea 1, 00184 Roma',
            'latitude' => '41.89075',
            'longitude' => '12.49805',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 90,
            'description' => 'Appartamento moderno con vista sul colosseo',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Appartamento a due passi dal Colosseo',
            'address' => 'Via Celimontana, 34, 00184 Roma RM',
            'latitude' => '41.88794',
            'longitude' => '12.49638',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Piccolo Appartamento a due passi dal colosseo',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Appartamento zona stazione termini',
            'address' => 'Via Giovanni Amendola, 57, 00185 Roma RM',
            'latitude' => '41.89994',
            'longitude' => '12.49969',
            'beds' => 4,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 110,
            'description' => 'Appartamento spazioso dotato di tutti i confort, vicino alla stazione',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Appartamento Tufello',
            'address' => 'Via delle Vigne Nuove, 45, 00139 Roma RM',
            'latitude' => '41.94708',
            'longitude' => '12.53715',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 70,
            'description' => 'Piccolo Appartamento idele per le coppie in zona Tufello',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Suite di lusso vicino al Pantheon',
            'address' => 'P.za di Pietra, 26, 00186 Roma RM',
            'latitude' => '41.89997',
            'longitude' => '12.47892',
            'beds' => 1,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 80,
            'description' => 'Suite Moderna dotata di tutti i confort, con vista sul Pantheon',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Stanza Pigneto',
            'address' => 'Via Prenestina, 42, 00176 Roma RM',
            'latitude' => '41.8912',
            'longitude' => '12.51976',
            'beds' => 1,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 20,
            'description' => 'stanza luminosa zona pigneto ideale per universitari',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'B&B a 2 passi da Roma',
            'address' => 'Viale Odone Belluzzi, 223, 00128 Roma RM',
            'latitude' => '41.77962',
            'longitude' => '12.42846',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 35,
            'description' => 'B&B vicino alla Riserva Naturale Statale Tenuta di Castelporziano, un luogo magnifico immerso nella natura.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Appartamento EUR',
            'address' => 'Viale Europa, 170, 00144 Roma RM',
            'latitude' => '41.83139',
            'longitude' => '12.46663',
            'beds' => 5,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Appartamento Spazioso ideale per aziende in piena zona EUR',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Stanza San Basilio',
            'address' => 'Via Cingoli, 15, 00156 Roma RM',
            'latitude' => '41.94131',
            'longitude' => '12.58505',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 20,
            'description' => 'Stanza zona san basilio con bagno indipendente',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Suite Trevi',
            'address' => 'Vicolo Scanderbeg, 00187 Roma RM',
            'latitude' => '41.90058',
            'longitude' => '12.48494',
            'beds' => 1,
            'rooms' => 1,
            'bathrooms' => 2,
            'sq_meters' => 100,
            'description' => 'Suite lussusissima nel centro storico romano a due passi dalla Fontana di Trevi, vista fontana di Trevi',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Appartamento Prati',
            'address' => 'Via Cola di Rienzo, 00192 Roma RM',
            'latitude' => '41.90911',
            'longitude' => '12.46989',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 100,
            'description' => 'Appartamento moderno in una zona esclusiva di Roma',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'B&B BioParco',
            'address' => 'Via Ulisse Aldrovandi, 15, 00197 Roma RM',
            'latitude' => '41.91864',
            'longitude' => '12.48493',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 40,
            'description' => 'B&B vicino al BioParco di Roma con bagno indipendente',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento la Breccia',
            'address' => 'Corso d\'Italia, 108, 00187 Roma RM',
            'latitude' => '41.91004',
            'longitude' => '12.50084',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 80,
            'description' => 'Appartamento Storico dotato di tutti i confort',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Guidonia\'s House',
            'address' => 'Via Lago Dei Tartari, 00012 Guidonia RM',
            'latitude' => '41.9581',
            'longitude' => '12.70342',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 150,
            'description' => 'Casa molto luminosa vicino zona industriale di guidonia ',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'La casa di Nerone',
            'address' => 'Via Bagnoregio, 00189 Roma RM',
            'latitude' => '41.97142',
            'longitude' => '12.43998',
            'beds' => 6,
            'rooms' => 4,
            'bathrooms' => 3,
            'sq_meters' => 160,
            'description' => 'Appartamento molto spazioso dotato di cucina abitabile e 2 stanze matrimoniali',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Stanza Aeroporto',
            'address' => 'Viale J. F. Kennedy, 161, 00043 Ciampino RM',
            'latitude' => '41.81155',
            'longitude' => '12.59379',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 35,
            'description' => 'Una stanza pensata per chi deve passare una notte prima di un viaggio',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento Forza Roma',
            'address' => 'Via Gustavo D\'Arpe, 00128 Roma RM',
            'latitude' => '41.76476',
            'longitude' => '12.47745',
            'beds' => 5,
            'rooms' => 4,
            'bathrooms' => 2,
            'sq_meters' => 150,
            'description' => 'Appartamento vicino al campo di allenamento della AS Roma',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Stanza Biomedica',
            'address' => 'Via Danilo Gavagnin, 30, 00128 Selcetta RM',
            'latitude' => '41.76832',
            'longitude' => '12.47128',
            'beds' => 1,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 20,
            'description' => 'Stanza vicino campus biomedico, ideale per universitari',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Stanza stop & go',
            'address' => 'Via Portuense, 2460, 00054 Fiumicino RM',
            'latitude' => '41.78528',
            'longitude' => '12.27619',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 30,
            'description' => 'Stanza a pochi passi dall\'aeroporto di Fiumicino, ideale per chi deve fermarsi una notte prima di partire',
            'cover_image'=> 'https://placehold.co/600x400',
                    ],
        [
            'title' => 'Appartamento Cesaroni',
            'address' => 'Largo Angelo Fochetti, 357-307, 00154 Roma RM',
            'latitude' => '41.86708',
            'longitude' => '12.49568',
            'beds' => 5,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Appartamento moderno zona Garbatella, dotato di tutti i comfort',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
    ],



    'extras' => [
        [
            'name'=> 'cucina', 
            'color'=> '#7A3F98',
            'icon'=> '<i class="fa-solid fa-kitchen-set"></i>',
        ],
        [
            'name'=> 'wi-fi', 
            'color'=> '#2ECC71',
            'icon'=> '<i class="fa-solid fa-wifi"></i>',
        ],
        [
            'name'=> 'giardino', 
            'color'=> '#F39C12',
            'icon'=> '<i class="fa-solid fa-seedling"></i>',
        ],
        [
            'name'=> 'posto auto', 
            'color'=> '#3498DB',
            'icon'=> '<i class="fa-solid fa-square-parking"></i>',
        ],
        [
            'name'=> 'tv', 
            'color'=> '#E74C3C',
            'icon'=> '<i class="fa-solid fa-tv"></i>',
        ],
        [
            'name'=> 'piscina', 
            'color'=> '#1ABC9C',
            'icon'=> '<i class="fa-solid fa-person-swimming"></i>',
        ],
        [
            'name'=> 'aria condizionata', 
            'color'=> '#D35400',
            'icon'=> '<i class="fa-solid fa-wind"></i>',
        ],
        [
            'name'=> 'vista mare', 
            'color'=> '#8E44AD',
            'icon'=> '<i class="fa-solid fa-water"></i>',
        ],
    ],

    'sponsorships' => [
        [
            'price'=> 2.99,
            'duration' => 24,
            'name' => 'bronze',
             
        ],
        [
            'price'=> 5.99,
            'duration' => 72,
            'name' => 'silver',
        ],
        [
            'price'=>9.99,
            'duration' => 10,
            'name' => 'gold',
        ],
    ],

    'users' => [
        [
            'name' => 'Mario',
            'last_name' => 'Rossi',
            'email' => 'mario.rossi@example.com',
            'date_of_birth' => '1990-08-15',
            'password' => 'securepass1'
        ],
        [
            'name' => 'Anna',
            'last_name' => 'Bianchi',
            'email' => 'anna.bianchi@example.com',
            'date_of_birth' => '1985-03-22',
            'password' => 'strongpass2'
        ],
        [
            'name' => 'Luca',
            'last_name' => 'Verdi',
            'email' => 'luca.verdi@example.com',
            'date_of_birth' => '1995-11-10',
            'password' => 'safepass3'
        ],
        [
            'name' => 'Giulia',
            'last_name' => 'Neri',
            'email' => 'giulia.neri@example.com',
            'date_of_birth' => '1988-06-05',
            'password' => 'secretword4'
        ],
        [
            'name' => 'Alessio',
            'last_name' => 'Giallo',
            'email' => 'alessio.giallo@example.com',
            'date_of_birth' => '1992-09-18',
            'password' => 'password123'
        ]
    ],


];